/**:
  ros__parameters:
    poses:
      - initial_pose
      - shutdown_pose
      - move_pose
      - detecting_pose
      - open_detecting_pose

    initial_pose:
      body_lift : 0.5
      head_pan : 0.0
      head_tilt : 0.0
      arm_left_shoulder_tilt : -0.52
      arm_left_upper_roll : -1.22
      arm_left_upper_flex : 0.0
      arm_left_elbow : 1.571
      arm_left_lower_flex : 0.0
      arm_left_wrist_tilt : 0.52
      arm_left_wrist_roll : 0.0
      arm_right_shoulder_tilt : -0.52
      arm_right_upper_roll : -1.22
      arm_right_upper_flex : 0.0
      arm_right_elbow : 1.571
      arm_right_lower_flex : 0.0
      arm_right_wrist_tilt : 0.52
      arm_right_wrist_roll : 0.0

    shutdown_pose:
      body_lift : 0.05
      head_pan : 0.0
      head_tilt : -0.78
      arm_left_shoulder_tilt : 0.0
      arm_left_upper_roll : -1.3
      arm_left_upper_flex : 0.0
      arm_left_elbow : 1.04
      arm_left_lower_flex : 0.0
      arm_left_wrist_tilt : 0.52
      arm_left_wrist_roll : 0.0
      arm_right_shoulder_tilt : 0.0
      arm_right_upper_roll : -1.3
      arm_right_upper_flex : 0.0
      arm_right_elbow : 1.04
      arm_right_lower_flex : 0.0
      arm_right_wrist_tilt : 0.52
      arm_right_wrist_roll : 0.0
      
    move_pose:
      body_lift: 0.50

      head_pan: 0.00
      head_tilt: 0.00

      arm_left_shoulder_tilt: -0.55
      arm_left_upper_roll: -1.57
      arm_left_upper_flex: -0.54
      arm_left_elbow: 2.77
      arm_left_lower_flex: -0.55
      arm_left_wrist_tilt: -1.57
      arm_left_wrist_roll: 0.00

      arm_right_shoulder_tilt: -0.55
      arm_right_upper_roll: -1.56
      arm_right_upper_flex: -0.56
      arm_right_elbow: 2.76
      arm_right_lower_flex: -0.55
      arm_right_wrist_tilt: -1.57
      arm_right_wrist_roll: 0.00

    detecting_pose:
      body_lift: 0.5

      head_pan: 0.0
      head_tilt: -0.52

      arm_left_shoulder_tilt: -0.55
      arm_left_upper_roll: -1.57
      arm_left_upper_flex: 0.0
      arm_left_elbow: 1.571
      arm_left_lower_flex: 0.0
      arm_left_wrist_tilt: -1.57
      arm_left_wrist_roll: 0.0

      arm_right_shoulder_tilt: -0.55
      arm_right_upper_roll: -1.57
      arm_right_upper_flex: 0.0
      arm_right_elbow: 1.571
      arm_right_lower_flex: 0.0
      arm_right_wrist_tilt: -1.57
      arm_right_wrist_roll: 0.0

    open_detecting_pose:
      body_lift: 0.5

      head_pan: 0.0
      head_tilt: -0.52

      arm_left_shoulder_tilt: -0.55
      arm_left_upper_roll: -1.57
      arm_left_upper_flex: 0.0
      arm_left_elbow: 1.571
      arm_left_lower_flex: -1.57
      arm_left_wrist_tilt: -1.57
      arm_left_wrist_roll: 0.0

      arm_right_shoulder_tilt: -0.55
      arm_right_upper_roll: -1.57
      arm_right_upper_flex: 0.0
      arm_right_elbow: 2.79
      arm_right_lower_flex: -1.57
      arm_right_wrist_tilt: -1.57
      arm_right_wrist_roll: 0.0

