/**:
  ros__parameters:
    poses:
      - initial_pose
      - detecting_pose

    initial_pose:
      body_lift : 0.5
      head_pan : 0.0
      head_tilt : 0.0
      arm_left_shoulder_tilt : -0.55
      arm_left_upper_roll : -1.571
      arm_left_upper_flex : 0.0
      arm_left_elbow : 1.33
      arm_left_lower_flex : 0.0
      arm_left_wrist_tilt : 0.0
      arm_left_wrist_roll : 0.0
      arm_right_shoulder_tilt : -0.55
      arm_right_upper_roll : -1.571
      arm_right_upper_flex : 0.0
      arm_right_elbow : 1.33
      arm_right_lower_flex : 0.0
      arm_right_wrist_tilt : 0.0
      arm_right_wrist_roll : 0.0

    detecting_pose:
      body_lift : 0.5
      head_pan : 0.0
      head_tilt : -0.41
      arm_left_shoulder_tilt : -0.6
      arm_left_upper_roll : -1.571
      arm_left_upper_flex : -1.571
      arm_left_elbow : 1.571
      arm_left_lower_flex : 0.0
      arm_left_wrist_tilt : 0.0
      arm_left_wrist_roll : 0.0
      arm_right_shoulder_tilt : -0.6
      arm_right_upper_roll : -1.571
      arm_right_upper_flex : -1.571
      arm_right_elbow : 1.571
      arm_right_lower_flex : 0.0
      arm_right_wrist_tilt : 0.0
      arm_right_wrist_roll : 0.0
