# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_left_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_left_shoulder_tilt_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_left_upper_flex_joint:
    has_velocity_limits: true
    max_velocity: 4.8099999999999996
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_left_upper_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_left_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_left_wrist_tilt_joint:
    has_velocity_limits: true
    max_velocity: 4.8099999999999996
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_right_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_right_shoulder_tilt_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_right_upper_flex_joint:
    has_velocity_limits: true
    max_velocity: 4.8099999999999996
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_right_upper_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_right_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_right_wrist_tilt_joint:
    has_velocity_limits: true
    max_velocity: 4.8099999999999996
    has_acceleration_limits: true
    max_acceleration: 0.1
  body_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.84999999999999998
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_left_finger_c_ip_joint:
    has_velocity_limits: true
    max_velocity: 11.031000000000001
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_left_finger_c_mcp_joint:
    has_velocity_limits: true
    max_velocity: 11.031000000000001
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_left_finger_l_dip_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_left_finger_l_mcp_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_left_finger_l_pip_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_left_finger_r_dip_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_left_finger_r_pip_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_right_finger_c_ip_joint:
    has_velocity_limits: true
    max_velocity: 11.031000000000001
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_right_finger_c_mcp_joint:
    has_velocity_limits: true
    max_velocity: 11.031000000000001
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_right_finger_l_dip_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_right_finger_l_mcp_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_right_finger_l_pip_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_right_finger_r_dip_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  hand_right_finger_r_pip_joint:
    has_velocity_limits: true
    max_velocity: 11.031179004
    has_acceleration_limits: true
    max_acceleration: 0.1
  virtual_joint/x:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  virtual_joint/y:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  virtual_joint/theta:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0