/**/controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    head_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_left_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_right_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_left_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_right_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    body_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    wheel_steer_position_controller:
      type: position_controllers/JointGroupPositionController

    wheel_drive_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


/**/head_position_controller:
  ros__parameters:
    joints:
      - head_pan_joint
      - head_tilt_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

/**/arm_left_position_controller:
  ros__parameters:
    joints:
      - arm_left_shoulder_tilt_joint
      - arm_left_upper_roll_joint
      - arm_left_upper_flex_joint
      - arm_left_elbow_joint
      - arm_left_lower_flex_joint
      - arm_left_wrist_tilt_joint
      - arm_left_wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

/**/arm_right_position_controller:
  ros__parameters:
    joints:
      - arm_right_shoulder_tilt_joint
      - arm_right_upper_roll_joint
      - arm_right_upper_flex_joint
      - arm_right_elbow_joint
      - arm_right_lower_flex_joint
      - arm_right_wrist_tilt_joint
      - arm_right_wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

/**/hand_left_position_controller:
  ros__parameters:
    joints:
      - hand_left_finger_l_mcp_joint
      - hand_left_finger_l_dip_joint
      - hand_left_finger_l_pip_joint
      - hand_left_finger_c_mcp_joint
      - hand_left_finger_c_ip_joint
      - hand_left_finger_r_dip_joint
      - hand_left_finger_r_pip_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

/**/hand_right_position_controller:
  ros__parameters:
    joints:
      - hand_right_finger_l_mcp_joint
      - hand_right_finger_l_dip_joint
      - hand_right_finger_l_pip_joint
      - hand_right_finger_c_mcp_joint
      - hand_right_finger_c_ip_joint
      - hand_right_finger_r_dip_joint
      - hand_right_finger_r_pip_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

/**/body_position_controller:
  ros__parameters:
    joints:
      - body_lift_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

/**/wheel_steer_position_controller:
  ros__parameters:
    joints:
      - wheel_steer_f_l_joint
      - wheel_steer_f_r_joint
      - wheel_steer_b_l_joint
      - wheel_steer_b_r_joint

/**/wheel_drive_velocity_controller:
  ros__parameters:
    joints:
      - wheel_drive_f_l_joint
      - wheel_drive_f_r_joint
      - wheel_drive_b_l_joint
      - wheel_drive_b_r_joint
