image_width: 640
image_height: 480
camera_name: hand_right_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [239.59393,   0.     , 298.30787,
           0.     , 239.9392 , 250.48436,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.008604, -0.009830, -0.002168, -0.000633, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [224.44043,   0.     , 290.98142,   0.     ,
           0.     , 234.73035, 248.92426,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
