image_width: 640
image_height: 480
camera_name: hand_left_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [242.22058,   0.     , 322.72581,
           0.     , 243.31355, 216.81771,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.004787, -0.015974, -0.001357, -0.000844, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [241.84213,   0.     , 322.22157,   0.     ,
           0.     , 242.50943, 216.68747,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
