/**:
    ros__parameters:
      # video_device: "/dev/video0"
      framerate: 5.0
      io_method: "mmap"
      # frame_id: "hand_left_camera_optical_frame"
      pixel_format: "mjpeg2rgb"  # ELP-USBGS1200P01-H120 outputs MJPEG
      av_device_format: "YUV422P"
      image_width: 640
      image_height: 480
      camera_name: "hand_left_camera"
      # camera_info_url: "package://sobit_home_bringup/config/hand_left_cam_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
      skip_device_check: true
